### ISSUE TITLE
ERROR: Directory /var/opt/jfrog/artifactory has bad permissions for user 'artifactory'

### ISSUE THREAD

**Issue by Robyngithub** [jfrog/artifactory-docker-examples#123]
How to give write permission -- please suggest

**Comment by Robyngithub** [comment]
> How to give write permission -- please suggest

Preparing to run Artifactory in Docker
=====================================
2018-10-08 18:49:38   [44 entrypoint-artifactory.sh] Dockerfile for this image can found inside the container.
2018-10-08 18:49:38   [45 entrypoint-artifactory.sh] To view the Dockerfile: 'cat /docker/artifactory-oss/Dockerfile.artifactory'.
2018-10-08 18:49:38   [50 entrypoint-artifactory.sh] Checking open files and processes limits
2018-10-08 18:49:38   [53 entrypoint-artifactory.sh] Current max open files is 32000
2018-10-08 18:49:38   [65 entrypoint-artifactory.sh] Current max open processes is 65535
2018-10-08 18:49:38   [75 entrypoint-artifactory.sh] Checking if /var/opt/jfrog/artifactory is mounted
2018-10-08 18:49:38   [80 entrypoint-artifactory.sh] /var/opt/jfrog/artifactory is mounted
2018-10-08 18:49:38   [92 entrypoint-artifactory.sh] Testing directory (/opt/jfrog/artifactory) has read/write permissions
2018-10-08 18:49:38  [100 entrypoint-artifactory.sh] /opt/jfrog/artifactory has read/write permissions for artifactory
2018-10-08 18:49:38   [92 entrypoint-artifactory.sh] Testing directory (/var/opt/jfrog/artifactory) has read/write permissions
/entrypoint-artifactory.sh: line 97: /var/opt/jfrog/artifactory/test-permissions: Permission denied
2018-10-08 18:49:38  [113 entrypoint-artifactory.sh] ###########################################################
2018-10-08 18:49:38  [114 entrypoint-artifactory.sh] /var/opt/jfrog/artifactory is NOT writable!
2018-10-08 18:49:38  [115 entrypoint-artifactory.sh] Directory: /var/opt/jfrog/artifactory, permissions: 755, owner: root, group: root
2018-10-08 18:49:38  [116 entrypoint-artifactory.sh] Mounted directory must be writable by user 'artifactory' (id 1030)
2018-10-08 18:49:38  [117 entrypoint-artifactory.sh] ###########################################################
2018-10-08 18:49:38   [34 entrypoint-artifactory.sh] ERROR: Directory /var/opt/jfrog/artifactory has bad permissions for user 'artifactory'

**Comment by jainishshah17** [comment]
@Robyngithub Can you provide more detail about your environment? Which installer are you using compose/helm/kubernetes?

**Comment by Robyngithub** [comment]
using docker-compose 

artifactory-oss.yml

version: '2'
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:latest
    container_name: artifactory
    ports:
     - 8081:8081
    volumes:
     - /opt/builder/softwares/artifactory:/var/opt/jfrog/artifactory
#    Add extra Java options by uncommenting the following lines
#    environment:
#     - EXTRA_JAVA_OPTIONS=-Xmx4g
    restart: always
    ulimits:
      nproc: 65535
      nofile:
        soft: 32000
        hard: 40000

**Comment by jainishshah17** [comment]
@Robyngithub Did you run `prepareHostEnv.sh` as mentioned in documentation? https://github.com/jfrog/artifactory-docker-examples/tree/master/docker-compose/artifactory#artifactory-oss

**Comment by Robyngithub** [comment]
Not working ... command not running

[root@devops ~]# sudo ./prepareHostEnv.sh -t pro -c
sudo: ./prepareHostEnv.sh: command not found
[root@devops ~]# sudo ./prepareHostEnv.sh -h
sudo: ./prepareHostEnv.sh: command not found
[root@devops ~]# sudo ./prepareHostEnv.sh -t oss -c
sudo: ./prepareHostEnv.sh: command not found
[root@devops ~]#

**Comment by jainishshah17** [comment]
@Robyngithub I think you are not in the proper directory.  You need to run this script --> https://github.com/jfrog/artifactory-docker-examples/blob/master/docker-compose/artifactory/prepareHostEnv.sh

**Comment by Robyngithub** [comment]
no luck i tried running the script for changing permission for the /var/opt folder.

**Comment by Mugenprime** [comment]
Hi any progress with this issue? I'm also running into the same issue running the script and also getting permission issues when deploying the docker-compose file.

**Comment by eldada** [comment]
@Mugenprime - can you test this with Artifactory version 6.6.1? This version includes some improvements to the permissions tests.

**Comment by Mugenprime** [comment]
> @Mugenprime - can you test this with Artifactory version 6.6.1? This version includes some improvements to the permissions tests.

Hi Eldada - I'm currently using the 6.6.1 images. Also when i run the prepareHostEnv.sh script i get the following error message:

sudo ./prepareHostEnv.sh -t pro -d ./data
Using a custom root data dir: ./data
./prepareHostEnv.sh: line 111: [: =: unary operator expected
Creating ./data
Copying needed files to directories
Artifactory configuration files
cp: cannot stat './../../files/access': No such file or directory

ERROR: Copy failed

**Comment by eldada** [comment]
I pushed a fix to the `[: =: unary operator expected`.
As for the `cp: cannot stat './../../files/access': No such file or directory` - I suspect you either don't have the full copy of the repository cloned or your directory structure is manipulated. 
Make sure you have the latest sources and do not modify the tree structure.
And, as @jainishshah17 noted before - run the script from within the `REPO_ROOT/docker-compose/artifactory/` directory.

**Comment by Mugenprime** [comment]
> I pushed a fix to the `[: =: unary operator expected`.
> As for the `cp: cannot stat './../../files/access': No such file or directory` - I suspect you either don't have the full copy of the repository cloned or your directory structure is manipulated.
> Make sure you have the latest sources and do not modify the tree structure.
> And, as @jainishshah17 noted before - run the script from within the `REPO_ROOT/docker-compose/artifactory/` directory.

I've resolved the "cp: cannot..." issue however, I'm still having issues with folder permissions. I seem to be able to overcome some of the error messages by specifying the user in the compose yml file and setting it to root, but i then get a master.key file currently missing error. I've opted to go for named docker volumes and that seems to be working without any permission alterations. Are there any reservations why named volumes are not recommended for persistent storage? Also is there currently any straightforward way to connect Artifactory container to an external remote Postgresql database with SSL connection?

**Comment by Mugenprime** [comment]
Thanks for the quick response. From my understanding using a container to host a database is not recomended for production usage. Is this the case with the current build of Artifactory?

**Comment by eldada** [comment]
There is no guidance. The examples are provided as examples 😉 
If the database app is in a container but the storage is a mounted volume (which is managed as production storage), IMHO this is a valid production scenario.

**Comment by eldada** [comment]
@Mugenprime - do you have any open issues or can we close this?

**Comment by Mugenprime** [comment]
@eldada - is there currently a resolution on with the permission issues with the image and user 1030?

**Comment by eldada** [comment]
Yes. With Artifactory 6.6.X you should be able to.
You can pass a custom user/group ids to the container. In docker compose, you can add the `uid` and `gid`.
Docker run: `docker run .... --user 1234:4321`
Docker compose:
```
  user: "1234:4321"
```

**Comment by eldada** [comment]
Great. Update us on the results.

**Comment by jghankins** [comment]
> @eldada Ok will give it a try later this afternoon. Thanks for your help.

Any update on your results?

**Comment by eldada** [comment]
@Mugenprime do you have formal results?

**Comment by marcuschaney** [comment]
I'm having this same issue trying to run Artifactory 6.7.3 using compose (stuck in the restarting loop). Error below:

 ###########################################################
 /var/opt/jfrog/artifactory DOES NOT have proper permissions for user 'artifactory' (id 1030)
 Directory: /var/opt/jfrog/artifactory, permissions: 755, owner: root, group: root
 Mounted directory must have read/write permissions for user 'artifactory' (id 1030)
 ###########################################################
 ERROR: Directory /var/opt/jfrog/artifactory has bad permissions for user 'artifactory' (id 1030)

I'm a novice with Docker and Artifactory.

**Comment by eldada** [comment]
Will continue in #144
